# GNU File, Shell, and Text utilities
brew "coreutils"
# Modern, maintained replacement for ls
brew "eza"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# GitHub command-line tool
brew "gh"
# Git extension for versioning large files
brew "git-lfs"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Perform tasks asynchronously without external tools
brew "zsh-async"
# Pretty, minimal and fast ZSH prompt
brew "pure"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
# Cross-shell prompt for astronauts
brew "starship"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Internet file retriever
brew "wget"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Zsh port of Fish shell's history search
brew "zsh-history-substring-search"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Display management tool
cask "betterdisplay"
# Open-source code editor
cask "visual-studio-code"
