command_timeout = 10000
palette = "github-light-default"

[palettes.github-light-default]
fg = "#24292f"
muted = "#6a737d"
accent = "#0366d6"
keyword = "#d73a49"
function = "#6f42c1"
string = "#032f62"
number = "#005cc5"
class = "#005cc5"
variable = "#e36209"
constant = "#005cc5"
tag = "#22863a"
attribute = "#6f42c1"
punctuation = "#24292f"
invalid = "#d73a49"
bg = "#ffffff"
selection = "#c8e1ff"

[character]
success_symbol = "[❯](tag)"
error_symbol = "[❯](keyword)"
vimcmd_symbol = "[❮](muted)"

[directory]
read_only = " 󰌾"
style = "function"

[cmd_duration]
style = "variable"

[hostname]
ssh_symbol = " "
style = "variable"

[aws]
symbol = "  "
style = "variable"

[git_branch]
symbol = " "
style = "keyword"

[fossil_branch]
symbol = " "
style = "keyword"

[hg_branch]
symbol = " "
style = "keyword"

[buf]
symbol = " "
style = "class"

# --- Language & Tools ---
[c]
symbol = " "
style = "class"

[conda]
symbol = " "
style = "class"

[crystal]
symbol = " "
style = "class"

[dart]
symbol = " "
style = "class"

[docker_context]
symbol = " "

[dotnet]
symbol = "󰪮 "
style = "class"
format = '(via [$symbol($version )(󰁔 $tfm )]($style))'

[elixir]
symbol = " "
style = "class"

[elm]
symbol = " "
style = "class"

[fennel]
symbol = " "
style = "class"

[golang]
symbol = " "
style = "class"

[guix_shell]
symbol = " "
style = "class"

[haskell]
symbol = " "
style = "class"

[haxe]
symbol = " "
style = "class"

[java]
symbol = " "
style = "class"

[julia]
symbol = " "
style = "class"

[kotlin]
symbol = " "
style = "class"

[lua]
symbol = " "
style = "class"

[memory_usage]
symbol = "󰍛 "
style = "class"

[meson]
symbol = "󰔷 "
style = "class"

[nim]
symbol = "󰆥 "
style = "class"

[nix_shell]
symbol = " "
style = "class"

[nodejs]
symbol = " "
style = "class"

[ocaml]
symbol = " "
style = "class"

[package]
symbol = "󰏗 "
style = "class"

[perl]
symbol = " "
style = "class"

[php]
symbol = " "
style = "class"

[pijul_channel]
symbol = " "
style = "class"

[python]
symbol = " "
style = "class"

[rlang]
symbol = "󰟔 "
style = "class"

[ruby]
symbol = " "
style = "class"

[rust]
symbol = " "
style = "class"

[scala]
symbol = " "
style = "class"

[swift]
symbol = " "
style = "class"

[zig]
symbol = " "
style = "class"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
