command_timeout = 10000
palette = "colors"

[palettes.colors]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](subtext1)"

[directory]
read_only = " 󰌾"
style = "lavender"

[cmd_duration]
style = "yellow"

[hostname]
ssh_symbol = " "
style = "yellow"

[aws]
symbol = "  "
style = "yellow"

[git_branch]
symbol = " "
style = "mauve"

[fossil_branch]
symbol = " "
style = "mauve"

[hg_branch]
symbol = " "
style = "mauve"

[buf]
symbol = " "
style = "peach"

[c]
symbol = " "
style = "peach"

[conda]
symbol = " "
style = "peach"

[crystal]
symbol = " "
style = "peach"

[dart]
symbol = " "
style = "peach"

[docker_context]
symbol = " "

[dotnet]
symbol = "󰪮 "
style = "peach"
format = '(via [$symbol($version )(󰁔 $tfm )]($style))'

[elixir]
symbol = " "
style = "peach"

[elm]
symbol = " "
style = "peach"

[fennel]
symbol = " "
style = "peach"

[golang]
symbol = " "
style = "peach"

[guix_shell]
symbol = " "
style = "peach"

[haskell]
symbol = " "
style = "peach"

[haxe]
symbol = " "
style = "peach"

[java]
symbol = " "
style = "peach"

[julia]
symbol = " "
style = "peach"

[kotlin]
symbol = " "
style = "peach"

[lua]
symbol = " "
style = "peach"

[memory_usage]
symbol = "󰍛 "
style = "peach"

[meson]
symbol = "󰔷 "
style = "peach"

[nim]
symbol = "󰆥 "
style = "peach"

[nix_shell]
symbol = " "
style = "peach"

[nodejs]
symbol = " "
style = "peach"

[ocaml]
symbol = " "
style = "peach"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
style = "peach"

[perl]
symbol = " "
style = "peach"

[php]
symbol = " "
style = "peach"

[pijul_channel]
symbol = " "
style = "peach"

[python]
symbol = " "
style = "peach"

[rlang]
symbol = "󰟔 "
style = "peach"

[ruby]
symbol = " "
style = "peach"

[rust]
symbol = " "
style = "peach"

[scala]
symbol = " "
style = "peach"

[swift]
symbol = " "
style = "peach"

[zig]
symbol = " "
style = "peach"
