command_timeout = 10000

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](gray)"

[directory]
read_only = " 󰌾"
style = "blue"

[cmd_duration]
style = "orange"

[hostname]
ssh_symbol = " "
style = "orange"

[aws]
symbol = "  "
style = "orange"

[git_branch]
symbol = " "
style = "red"

[fossil_branch]
symbol = " "
style = "red"

[hg_branch]
symbol = " "
style = "red"

[buf]
symbol = " "
style = "purple"

[c]
symbol = " "
style = "purple"

[conda]
symbol = " "
style = "purple"

[crystal]
symbol = " "
style = "purple"

[dart]
symbol = " "
style = "purple"

[docker_context]
symbol = " "

[dotnet]
symbol = "󰪮 "
style = "purple"
format = '(via [$symbol($version )(󰁔 $tfm )]($style))'

[elixir]
symbol = " "
style = "purple"

[elm]
symbol = " "
style = "purple"

[fennel]
symbol = " "
style = "purple"

[golang]
symbol = " "
style = "purple"

[guix_shell]
symbol = " "
style = "purple"

[haskell]
symbol = " "
style = "purple"

[haxe]
symbol = " "
style = "purple"

[java]
symbol = " "
style = "purple"

[julia]
symbol = " "
style = "purple"

[kotlin]
symbol = " "
style = "purple"

[lua]
symbol = " "
style = "purple"

[memory_usage]
symbol = "󰍛 "
style = "purple"

[meson]
symbol = "󰔷 "
style = "purple"

[nim]
symbol = "󰆥 "
style = "purple"

[nix_shell]
symbol = " "
style = "purple"

[nodejs]
symbol = " "
style = "purple"

[ocaml]
symbol = " "
style = "purple"

[package]
symbol = "󰏗 "
style = "purple"

[perl]
symbol = " "
style = "purple"

[php]
symbol = " "
style = "purple"

[pijul_channel]
symbol = " "
style = "purple"

[python]
symbol = " "
style = "purple"

[rlang]
symbol = "󰟔 "
style = "purple"

[ruby]
symbol = " "
style = "purple"

[rust]
symbol = " "
style = "purple"

[scala]
symbol = " "
style = "purple"

[swift]
symbol = " "
style = "purple"

[zig]
symbol = " "
style = "purple"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "