[general]
import = [
  #"~/.config/alacritty/themes/Monokai Pro",
  "~/.config/alacritty/themes/Monokai Pro Light"
]

[window]
dimensions = { columns = 125, lines = 45 }
decorations = "full"
opacity = 1.0
startup_mode = "Windowed"

[scrolling]
history = 5000

[font]
size = 13

[font.normal]
family = "Berkeley Mono Variable"
style = "Book"

[font.bold]
family = "Berkeley Mono Variable"
style = "ExtraBold"

[font.italic]
family = "Berkeley Mono Variable"
style = "Oblique"

[font.bold_italic]
family = "Berkeley Mono Variable"
style = "ExtraBold Oblique"

# [font.normal]
# family = "MonoLisa"
# style = "Regular"

# [font.bold]
# family = "MonoLisa"
# style = "Bold"

# [font.italic]
# family = "MonoLisa"
# style = "Italic"

# [font.bold_italic]
# family = "MonoLisa"
# style = "Bold Italic"


[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
shell = { program = "/opt/homebrew/bin/fish" }